---
stages:
  - kics-scan

test:
  stage: kics-scan
  script:
    - docker run $CI_REGISTRY_IMAGE:latest --scan-repo ${TEST_REPOSITORY} --gitlab-hostname ${GITLAB_HOSTNAME} --gitlab-access-token ${GITLAB_ACCESS_TOKEN}
  needs:
    - build
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - changes:
        - Dockerfile
        - requirements.txt
        - repo_scanner.py

scan:
  stage: kics-scan
  script:
    - docker run $CI_REGISTRY_IMAGE:latest --gitlab-hostname ${GITLAB_HOSTNAME} --gitlab-access-token ${GITLAB_ACCESS_TOKEN}
  needs:
    - build
    - test
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

build:
  stage: kics-scan
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - changes:
        - Dockerfile
        - requirements.txt
        - repo_scanner.py
