---
stages:
  - kics-scan

.docker-login: &docker-login
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

test:
  <<: *docker-login
  stage: kics-scan
  script:
    - docker run $CI_REGISTRY_IMAGE:latest --scan-repo ${TEST_REPOSITORY} --gitlab-hostname ${GITLAB_HOSTNAME} --gitlab-access-token ${GITLAB_ACCESS_TOKEN}
  needs:
    - build
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $TEST_SCAN == "true"

scan:
  <<: *docker-login
  stage: kics-scan
  script:
    - docker run $CI_REGISTRY_IMAGE:latest --gitlab-hostname ${GITLAB_HOSTNAME} --gitlab-access-token ${GITLAB_ACCESS_TOKEN}
  needs:
    - build
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $LIVE_SCAN == "true"

build:
  <<: *docker-login
  stage: kics-scan
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
